# Generated by Django 5.2.4 on 2025-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
