# Generated by Django 5.2.4 on 2025-07-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/resumes'),
        ),
    ]
